### ISSUE TITLE
An entry with the same key already exists

### ISSUE THREAD

**Issue by ghost** [Krusen/BencodeNET#33]
NOTE: I have no idea what's in this torrent or whether it's malicious, it's one from a recent large dump.

This should probably throw an `InvalidTorrentException` instead. qBittorrent loads it fine fwiw

![image](https://user-images.githubusercontent.com/159567/36639846-fb6f59d8-1a68-11e8-80cb-aed44dbc0521.png)

[0ad2296131a3e29fb95e365393372c7f506c680a.torrent.gz](https://github.com/Krusen/BencodeNET/files/1755851/0ad2296131a3e29fb95e365393372c7f506c680a.torrent.gz)

**Comment by Krusen** [comment]
The issue here is the two `123` keys in the `info` dictionary.

![image](https://user-images.githubusercontent.com/1381368/36640243-2ce69fc4-1a1b-11e8-8836-a72e5f319ec2.png)

This will now throw a `InvalidBencodeException<BDictionary>` with more detailed exception messages.

Exception message:
```
Failed to parse BDictionary. Could not parse dictionary value for the key 'info'.
There needs to be a value for each key. The dictionary starts at position 0.
```

InnerException message:
```
Failed to parse BDictionary. The dictionary already contains the key '123'.
Duplicate keys are not supported. The dictionary starts at position 608. 
```

The new version will be available soon.
