### ISSUE TITLE
CalculateInfoHash probably not thread safe

### ISSUE THREAD

**Issue by SuRGeoNix** [Krusen/BencodeNET#50]
Minor issue in your case, but you might want to consider fixing this. SHA1 is not thread safe if it not declared as public static.

https://stackoverflow.com/questions/26592596/why-does-sha1-computehash-fail-under-high-load-with-many-threads

I had issues with sha1 but I was using it under really high loads for piece hash validation and I came across this issue.

You could just declared your sha1 (in TorrentUtil.cs) to ensure thread-safety, like this:-

`public  static SHA1 sha1 = new SHA1Managed();`

**Comment by Krusen** [comment]
Hi, sorry for taking so long to get back to you.

Looking at your link it looks like the issue mentioned in those cases is actually caused by the SHA1 instance being static and shared between threads, but in `TorrentUtil.cs` it's a new instance being created each time.

I don't see any obvious ways for that to be related to your issue.

**Comment by SuRGeoNix** [comment]
You are absolutely right, that was my misunderstanding with my project (about bittorrent sha1 validation) that was causing SHA1 to fail because of actually receiving invalid data from "broken" clients / phony packets.
